/*
 * Generated by gdbus-codegen 2.56.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __EXAMPLE_H__
#define __EXAMPLE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.test.example */

#define EXAMPLE_TYPE_EXAMPLE (example_example_get_type ())
#define EXAMPLE_EXAMPLE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EXAMPLE_TYPE_EXAMPLE, ExampleExample))
#define EXAMPLE_IS_EXAMPLE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EXAMPLE_TYPE_EXAMPLE))
#define EXAMPLE_EXAMPLE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), EXAMPLE_TYPE_EXAMPLE, ExampleExampleIface))

struct _ExampleExample;
typedef struct _ExampleExample ExampleExample;
typedef struct _ExampleExampleIface ExampleExampleIface;

struct _ExampleExampleIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_add) (
    ExampleExample *object,
    GDBusMethodInvocation *invocation,
    gint arg_num1,
    gint arg_num2);

  gboolean (*handle_emitter) (
    ExampleExample *object,
    GDBusMethodInvocation *invocation);

  gboolean  (*get_status) (ExampleExample *object);

  void (*ping) (
    ExampleExample *object);

};

GType example_example_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *example_example_interface_info (void);
guint example_example_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void example_example_complete_add (
    ExampleExample *object,
    GDBusMethodInvocation *invocation,
    gint ans);

void example_example_complete_emitter (
    ExampleExample *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void example_example_emit_ping (
    ExampleExample *object);



/* D-Bus method calls: */
void example_example_call_add (
    ExampleExample *proxy,
    gint arg_num1,
    gint arg_num2,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean example_example_call_add_finish (
    ExampleExample *proxy,
    gint *out_ans,
    GAsyncResult *res,
    GError **error);

gboolean example_example_call_add_sync (
    ExampleExample *proxy,
    gint arg_num1,
    gint arg_num2,
    gint *out_ans,
    GCancellable *cancellable,
    GError **error);

void example_example_call_emitter (
    ExampleExample *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean example_example_call_emitter_finish (
    ExampleExample *proxy,
    GAsyncResult *res,
    GError **error);

gboolean example_example_call_emitter_sync (
    ExampleExample *proxy,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
gboolean example_example_get_status (ExampleExample *object);
void example_example_set_status (ExampleExample *object, gboolean value);


/* ---- */

#define EXAMPLE_TYPE_EXAMPLE_PROXY (example_example_proxy_get_type ())
#define EXAMPLE_EXAMPLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EXAMPLE_TYPE_EXAMPLE_PROXY, ExampleExampleProxy))
#define EXAMPLE_EXAMPLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), EXAMPLE_TYPE_EXAMPLE_PROXY, ExampleExampleProxyClass))
#define EXAMPLE_EXAMPLE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), EXAMPLE_TYPE_EXAMPLE_PROXY, ExampleExampleProxyClass))
#define EXAMPLE_IS_EXAMPLE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EXAMPLE_TYPE_EXAMPLE_PROXY))
#define EXAMPLE_IS_EXAMPLE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EXAMPLE_TYPE_EXAMPLE_PROXY))

typedef struct _ExampleExampleProxy ExampleExampleProxy;
typedef struct _ExampleExampleProxyClass ExampleExampleProxyClass;
typedef struct _ExampleExampleProxyPrivate ExampleExampleProxyPrivate;

struct _ExampleExampleProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ExampleExampleProxyPrivate *priv;
};

struct _ExampleExampleProxyClass
{
  GDBusProxyClass parent_class;
};

GType example_example_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ExampleExampleProxy, g_object_unref)
#endif

void example_example_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ExampleExample *example_example_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ExampleExample *example_example_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void example_example_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ExampleExample *example_example_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ExampleExample *example_example_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define EXAMPLE_TYPE_EXAMPLE_SKELETON (example_example_skeleton_get_type ())
#define EXAMPLE_EXAMPLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EXAMPLE_TYPE_EXAMPLE_SKELETON, ExampleExampleSkeleton))
#define EXAMPLE_EXAMPLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), EXAMPLE_TYPE_EXAMPLE_SKELETON, ExampleExampleSkeletonClass))
#define EXAMPLE_EXAMPLE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), EXAMPLE_TYPE_EXAMPLE_SKELETON, ExampleExampleSkeletonClass))
#define EXAMPLE_IS_EXAMPLE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EXAMPLE_TYPE_EXAMPLE_SKELETON))
#define EXAMPLE_IS_EXAMPLE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EXAMPLE_TYPE_EXAMPLE_SKELETON))

typedef struct _ExampleExampleSkeleton ExampleExampleSkeleton;
typedef struct _ExampleExampleSkeletonClass ExampleExampleSkeletonClass;
typedef struct _ExampleExampleSkeletonPrivate ExampleExampleSkeletonPrivate;

struct _ExampleExampleSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ExampleExampleSkeletonPrivate *priv;
};

struct _ExampleExampleSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType example_example_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ExampleExampleSkeleton, g_object_unref)
#endif

ExampleExample *example_example_skeleton_new (void);


G_END_DECLS

#endif /* __EXAMPLE_H__ */
